# Generated by Django 4.1 on 2022-10-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='project',
            name='manuals',
            field=models.FileField(blank=True, help_text='Manuals', null=True, upload_to='manuals/'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(null=True),
        ),
    ]
